### ISSUE TITLE
_writeGaugeWeight Documentation and Variable Naming

### ISSUE THREAD

**Issue by ElliotFriedman** [fei-protocol/flywheel-v2#26]
Function `_writeGaugeWeight()` is used in ERC20Gauges to update gauge weights. The mechanism around how this operates intuitively feels like you're maintaining two weights, one from the current and one from the previous cycle. However, the variable `previousCurrent` has a confusing name that doesn't explain what it actually does. Add a natspec comment explaining how things update based on the current and previous cycle and change the `previousCurrent` variable name to more accurately describe what is happening.

**Comment by Joeysantoro** [comment]
https://github.com/fei-protocol/flywheel-v2/pull/45
